CustomExceptions.java

class Demo extends Exception  {
	public Demo(String s) { 
        super(s); 
    } 
} 
public class CustomExceptions {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try
        { 
            throw new Demo("temp"); 
        } 
        catch (Demo d) 
        { 
            System.out.println("Caught"); 
            System.out.println(d.getMessage()); 
        } 

	}

}


FinallyDemo.java


public class FinallyDemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		int a=78,b=0,rs=0;
        try {
            rs = a / b;
        }
        catch(ArithmeticException Ex){
            System.out.print("\n\tError : " + Ex.getMessage());
        }
        finally{
            System.out.print("\n\tThe result is : " + rs);
        }

	}

}

ThrowDemo.java

public class ThrowDemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		int a=78,b=0,rs;

           try {
               if(b==0)        
            	   throw(new ArithmeticException("Can't divide by zero."));
               else
               {
                   rs = a / b;
                   System.out.print("\n\tThe result is : " + rs);
               }
           }
           catch(ArithmeticException Ex)
           {
               System.out.print("\n\tError : " + Ex.getMessage());
           }

           System.out.print("\n\tEnd of program.");

	}

}

ThrowsDemo.java

public class ThrowsDemo {
	 void Division() throws ArithmeticException {
         int a=78,b=0,rs;
         rs = a / b;
         System.out.print("\n\tThe result is : " + rs);
     }

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ThrowsDemo T = new ThrowsDemo();
        try {
           T.Division();
        }
        catch(ArithmeticException Ex) {
            System.out.print("\n\tError : " + Ex.getMessage());
        }
        System.out.print("\n\tEnd of program.");

	}

}
